name: ${project.name}
main: com.nuclearw.colortab.ColorTab
version: ${project.version}
author: NuclearW
description: ColorTab colors the tab user list based off the color of the prefix from PermissionsEx
depend: [PermissionsEx]
commands:
    ctmagic:
        description: Toggle magic name in tab list
        usage: |
            /<command> (user)
permissions:
    colortab.*:
        description: Gives access to all ColorTab commands
        children:
            colortab.magic: true
            colortab.magic.other: true
    colortab.magic:
        description: Allows you to toggle magic name on yourself
        default: op
    colortab.magic.other:
        description: Allows you to toggle magic name on others
        default: op